name: Deploy to Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway (Dev Environment)
        run: railway up --environment 3cec8fab-725c-443f-9bb5-cc5bdb0cd628 --service 9a7e4300-27e4-48c8-962c-403bfcf95533 -d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
